import type { CategoryType, Snapshot, Streamer } from "@/types/streamer";
// Entirely fictional channels, IDs, titles and metrics. Never seeded into the live catalog.
const examples: [string, string, string, CategoryType, string, string, number, string[]][] = [
  [
    "모카플레이",
    "오늘은 다이아 갈 수 있을까? ☕ 같이 달려요",
    "리그 오브 레전드",
    "GAME",
    "lol",
    "rift",
    12482,
    ["랭크", "소통"],
  ],
  [
    "루미",
    "작은 섬에 우리만의 마을 만들기 🌿",
    "마인크래프트",
    "GAME",
    "minecraft",
    "island",
    8230,
    ["힐링", "건축"],
  ],
  [
    "하늘바다",
    "노을 보면서 이야기해요. 오늘 하루는 어땠나요?",
    "Just Chatting",
    "ETC",
    "talk",
    "sunset",
    5146,
    ["소통", "일상"],
  ],
  [
    "도토리",
    "한 판만 더! 오늘의 마지막 치킨 도전",
    "배틀그라운드",
    "GAME",
    "pubg",
    "night",
    3892,
    ["FPS", "스쿼드"],
  ],
  [
    "여울",
    "비 오는 날, 잔잔한 피아노와 함께 🎹",
    "음악",
    "ETC",
    "music",
    "music",
    2148,
    ["음악", "힐링"],
  ],
  [
    "네온",
    "새 시즌 시작! 팀원들과 함께 경쟁전",
    "발로란트",
    "GAME",
    "valorant",
    "neon",
    1756,
    ["FPS", "경쟁전"],
  ],
  [
    "초록산책",
    "주말 경기 같이 보면서 응원해요 ⚽",
    "스포츠",
    "SPORTS",
    "sports",
    "stadium",
    946,
    ["축구", "소통"],
  ],
  [
    "별빛상점",
    "밤의 모험, 새로운 이야기를 시작합니다",
    "종합 게임",
    "GAME",
    "variety",
    "space",
    624,
    ["스토리", "첫플레이"],
  ],
  [
    "구름고래",
    "함께여서 즐거웠던 오늘의 모험",
    "마인크래프트",
    "GAME",
    "minecraft",
    "island",
    0,
    ["힐링"],
  ],
  ["소소한밤", "새벽의 조용한 수다", "Just Chatting", "ETC", "talk", "sunset", 0, ["소통"]],
  ["비트온", "신청곡 들으며 쉬어가는 시간", "음악", "ETC", "music", "music", 0, ["음악"]],
  ["라임", "이번 시즌도 즐겁게!", "리그 오브 레전드", "GAME", "lol", "rift", 0, ["랭크"]],
  ["우주먼지", "우주 탐험 일지 12일 차", "종합 게임", "GAME", "variety", "space", 0, ["스토리"]],
  [
    "오후네시",
    "따뜻한 차 한 잔과 그림 그리기",
    "Just Chatting",
    "ETC",
    "talk",
    "sunset",
    0,
    ["일상"],
  ],
  ["산들", "주말 스포츠 이야기", "스포츠", "SPORTS", "sports", "stadium", 0, ["축구"]],
  ["픽셀정원", "새로운 정원 만들기", "마인크래프트", "GAME", "minecraft", "island", 0, ["건축"]],
];
export function demoSnapshot(now = Date.now()): Snapshot {
  const at = new Date(now - 62000).toISOString();
  const streamers: Streamer[] = examples.map(
    (
      [channelName, liveTitle, categoryName, categoryType, categoryId, art, viewerCount, tags],
      i,
    ) => ({
      channelId: (i + 1).toString(16).padStart(32, "0"),
      channelName,
      channelImageUrl: null,
      verifiedMark: i < 6,
      status: i < 8 ? "ONLINE" : "OFFLINE",
      liveTitle,
      thumbnailUrl: `/art/${art}.svg`,
      viewerCount,
      openDate: new Date(now - (i + 1) * 37 * 60000).toISOString(),
      adult: i === 7,
      categoryType,
      categoryId,
      categoryName,
      tags,
      lastCheckedAt: at,
      lastSeenLiveAt: new Date(now - (i < 8 ? 62000 : (i - 6) * 3600000)).toISOString(),
      demo: true,
    }),
  );
  return { streamers, lastSuccessfulSync: at, lastAttemptFailed: false, mode: "demo" };
}
